### ISSUE TITLE
Getting Faraday::ConnectionFailed: Broken pipe when running Resource.import

### ISSUE THREAD

**Issue by T-Dnzt** [greencommons/commons#101]
I've had the issue both in local and in production. Anytime I run `Resource.import` from the console or from a rake task, I'm getting `Faraday::ConnectionFailed: Broken pipe`.

```
D, [2017-01-13T13:35:53.791263 #4] DEBUG -- :   Resource Load (1112.1ms)  SELECT  "resources".* FROM "resources" ORDER BY "resources"."id" ASC LIMIT $1  [["LIMIT", 1000]]
rake aborted!
Faraday::ConnectionFailed: Broken pipe
```

I'm not sure what's wrong, and I haven't looked into it yet since it doesn't prevent the application from working (it only makes the `reset_resource_index` task fail).

I'm planning to do some research and see if I can figure it out. Any insights appreciated!

**Comment by ptrikutam** [comment]
This is really strange. I assume it's referring to the connection for S3? Was there any S3 downtime? Or am I completely off here?

**Comment by T-Dnzt** [comment]
No, it should be related to ElasticSearch... The `import` method is to add all the records to the ElasticSearch index. It works fine for one but I'm getting this error every time I try to import everything.

**Comment by ptrikutam** [comment]
Haven't seen this one in a while. Closing for now.
