### ISSUE TITLE
ruby epub parsing issues

### ISSUE THREAD

**Issue by gtourtellot** [greencommons/commons#104]
FYI, for me, 16 of the Island Press epubs have parse issues using ruby  'epub/parser'.
Three of these files are legitimately bad (corresponding to the message "unable to locate end-of-central-directory record"), the other 13 epubs can actually parse correctly (as witnessed elsewhere).

"Error opening epub 9781597265171.epub: unable to locate end-of-central-directory record"
"Error opening epub 9781597265935.epub: unable to locate end-of-central-directory record"
"Error opening epub 9781610914529.epub: undefined method `refines=' for #<EPUB::Metadata::UnsupportedModel:0x007fa704b56e10>\nDid you mean?  readlines"
"Error opening epub 9781610914574.epub: undefined method `refines=' for #<EPUB::Metadata::UnsupportedModel:0x007fa703b02ac8>\nDid you mean?  readlines"
"Error opening epub 9781610914802.epub: undefined method `refines=' for #<EPUB::Metadata::UnsupportedModel:0x007fa703949920>\nDid you mean?  readlines"
"Error opening epub 9781610915007.epub: undefined method `refines=' for #<EPUB::Metadata::UnsupportedModel:0x007fa70301ff98>\nDid you mean?  readlines"
"Error opening epub 9781610915403.epub: unable to locate end-of-central-directory record"
"Error opening epub 9781610915762.epub: undefined method `refines=' for #<EPUB::Metadata::UnsupportedModel:0x007fa7049005f8>\nDid you mean?  readlines"
"Error opening epub 9781610915861.epub: undefined method `refines=' for #<EPUB::Metadata::UnsupportedModel:0x007fa704ab8c88>\nDid you mean?  readlines"
"Error opening epub 9781610916639.epub: undefined method `refines=' for #<EPUB::Metadata::UnsupportedModel:0x007fa7048522f0>\nDid you mean?  readlines"
"Error opening epub 9781610916677.epub: undefined method `refines=' for #<EPUB::Metadata::UnsupportedModel:0x007fa704ac47e0>\nDid you mean?  readlines"
"Error opening epub 9781610916684.epub: undefined method `refines=' for #<EPUB::Metadata::UnsupportedModel:0x007fa703a8b888>\nDid you mean?  readlines"
"Error opening epub 9781610916691.epub: undefined method `refines=' for #<EPUB::Metadata::UnsupportedModel:0x007fa704a71888>\nDid you mean?  readlines"
"Error opening epub 9781610916707.epub: undefined method `refines=' for #<EPUB::Metadata::UnsupportedModel:0x007fa70387ad28>\nDid you mean?  readlines"
"Error opening epub 9781610916714.epub: undefined method `refines=' for #<EPUB::Metadata::UnsupportedModel:0x007fa703a90270>\nDid you mean?  readlines"
"Error opening epub 9781610916745.epub: undefined method `refines=' for #<EPUB::Metadata::UnsupportedModel:0x007fa7028c6940>\nDid you mean?  readlines"

**Comment by T-Dnzt** [comment]
@ptrikutam Should we do a fresh import using the JSON ETL? Do you know if all the island press EPUBs are available in the JSON files? Also, if implementing the new ETLs fixed this, I guess we can close it.

**Comment by gtourtellot** [comment]
In terms of availability of the EPUB data as JSON files...all the island
press EPUBs on s3 that and are valid have a JSON file.  However, there are
3 invalid EPUBs in S3 (9781597265171.epub, 9781597265935.epub,
9781610915403.epub) there and there is no JSON file for those.

**Comment by ptrikutam** [comment]
Sure, thanks Thibault. Please remove all resources from the database and
re-import using the JSON ETL. Thanks!

**Comment by T-Dnzt** [comment]
Should I delete and re-import the groups as well?

**Comment by T-Dnzt** [comment]
Just ran the ETL:

```
SELECT COUNT(*) FROM "resources"
=> 7090
```

**Comment by ptrikutam** [comment]
Sure, sounds good @T-Dnzt

**Comment by T-Dnzt** [comment]
@gtourtellot Would it be possible, somehow, to link the JSON documents for groups and the ones for resources? We could link them through the creation of lists containing the related resources. 

There are more than 2000 groups to import, and none of them will have any related records. Also wondering about admin rights, for now I could just give the group admin status to one user, but what about later? It would be great to have the actual admin (in real life) of such groups be imported as well!

cc: @ptrikutam

**Comment by gtourtellot** [comment]
On Wed, Feb 1, 2017 at 11:49 PM, Thibault <notifications@github.com> wrote:

> @gtourtellot <https://github.com/gtourtellot> Would it be possible,
> somehow, to link the JSON documents for groups and the ones for resources?
> We could link them through the creation of lists containing the related
> resources.
>
Hi @T-Dnzt.  @pavan and I just spoke about this.  Yes, it should be
possible to create lists for purposes of making (at least some) groups have
some resources shown.  Right now it's not a very high priority, though.

> There are more than 2000 groups to import, and none of them will have any
> related records. Also wondering about admin rights, for now I could just
> give the group admin status to one user, but what about later? It would be
> great to have the actual admin (in real life) of such groups be imported as
> well!
>
I'll punt on answering this question, but am happy to play the role of
groups' admin if needed/helpful.

Also, note that this github issue could be closed now that EPUB parsing
errors aren't critical, since we have the JSON files.

**Comment by ptrikutam** [comment]
To chime in, basically we don't need to address this right now. When we've got a demo coming up we can decide the best way to incorporate resources on the Group pages, and which groups we want to use.

For what it's worth, there's two ways of approaching this:

1. Randomize the list creation for groups, using the Faker gem.
2. Someone goes through, picks a handful of groups, creates some lists manually (by collecting titles of resources) and sends it to GC developers in a plaintext format of sorts.

Either way, I think we can close this issue and we can leave the Group/Resource task for another day.
