### ISSUE TITLE
Use update_document method to re-index updated record 

### ISSUE THREAD

**Issue by T-Dnzt** [greencommons/commons#108]
I think we should separate the `create`/`update` callback [here](https://github.com/greencommons/commons/blob/master/app/models/resource.rb#L26) and start using the `update_document` from [there](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/lib/elasticsearch/model/indexing.rb#L389). I'm worried about duplicates and was able to produce a bug by updating a record, searching for its old name and still finding it even though it should have been de-indexed.

It would also be interesting to unify the way we interact with ES by not using the `ElasticSearch::Modal.client` directly and instead relying on the methods provided by [elasticsearch-rails](https://github.com/elastic/elasticsearch-rails).

[delete_document](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/lib/elasticsearch/model/indexing.rb#L357) could replace the three lines below for example.

```
  def remove
    if search_index_callbacks_enabled?
      Elasticsearch::Model.client.delete(
        index: model_name.constantize.index_name,
        type: model_name.downcase,
        id: id,
      )
    else
      log_callback_warning
    end
  end
```

@ptrikutam Let me know if that's something you'd like me to work on or not.

**Comment by ptrikutam** [comment]
I like this idea. One question: does the `update_document` method create a record in the index if it doesn't exist already? Judging from [this line](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/lib/elasticsearch/model/indexing.rb#L404) it seems like it does, but I wasn't sure.

How long do you think this will take you?

**Comment by T-Dnzt** [comment]
Yes, based on the code, it should index the record if it doesn't exist yet. I can run some tests before implementing it to double-check.

For the timeframe, since we already have the setup to create/delete from the index, it won't take more than an hour (probably much less).

**Comment by ptrikutam** [comment]
Got it. OK, yes please go ahead and implement this. Thanks!

**Comment by T-Dnzt** [comment]
The implementation ended up looking different from what I originally wanted to do, but the goal has been accomplished. I learned a lot about ES and the way we interact with it so that's a great point for the rest of the project. Closing this issue!

**Comment by ptrikutam** [comment]
Great, thanks.​
