### ISSUE TITLE
Run Rubocop as one of the checks for pull requests

### ISSUE THREAD

**Issue by T-Dnzt** [greencommons/commons#116]
We run CircleCI and HoundCI but we currently don't have anything checking Rubocop offenses. 

It would be great to have [Pronto](https://github.com/mmozuras/pronto) and [Pronto-Rubocop](https://github.com/mmozuras/pronto-rubocop) checking and leaving the offenses as comments.

/discuss

(And yes, it's totally because I forgot to run Rubocop for the latest PR I merged.)

**Comment by ptrikutam** [comment]
HoundCI should be validating Ruby offenses based on `.hound.yml` and commenting directly on PRs. I just checked and I think it wasn't activated to use that config. I just turned it back on. Thanks for bringing this to my attention -- let's see if this fixes things and comments appropriately, and if not we can look into what's going on and decide if we need to swtich.

**Comment by ptrikutam** [comment]
@T-Dnzt has rubocop been running for your PRs? I'm not seeing any hound violations but maybe that's because you're so on top of things :)

**Comment by T-Dnzt** [comment]
I've been very careful since I let some offenses get into master :p I'm going to test it today.

**Comment by T-Dnzt** [comment]
I just pushed some code with an offense but Hound didn't comment about it. In local, I have:

```
Offenses:

app/models/concerns/indexable.rb:13:7: W: Do not use prefix _ for a variable that is used.
      _changes = previous_changes.dup
      ^^^^^^^^

108 files inspected, 1 offense detected
```

In this [file](https://github.com/greencommons/commons/pull/120/files#diff-6a6bc351e5741fc7d0ac47a2748cb86bR13).

As you can see in the [PR](https://github.com/greencommons/commons/pull/120), nothing was raised :(

**Comment by T-Dnzt** [comment]
I did some research/checking and I don't see what's wrong with our current configuration - we should have Hound commenting the Rubocop offenses...

**Comment by ptrikutam** [comment]
:( yeah. I'm asking them about it here: https://twitter.com/ptrikutam/status/837066052643127299

**Comment by ptrikutam** [comment]
OK, heard back from the nice Hound folks :)

> hound is really finnicky about the format the .rubocop.yml file is set up with
> single vs double quotes, no quotes, etc
> take this version from the hound repo itself: https://github.com/houndci/hound/blob/master/spec/support/fixtures/thoughtbot_rubocop_config.yml
> use THAT file for one of the PR's you're trying out
> see if rubocop runs sucessfully then
> I'm betting it'll work

@T-Dnzt can you try that and see if it works?

**Comment by T-Dnzt** [comment]
@ptrikutam Just made a test pull request and indeed it's working with that specific configuration. I will try to fix ours and make it work. ;)

[PR for reference](https://github.com/greencommons/commons/pull/145).

**Comment by ptrikutam** [comment]
🙌
