### ISSUE TITLE
Alignment issues for Explore / Group List 

### ISSUE THREAD

**Issue by T-Dnzt** [greencommons/commons#122]
Currently, if one of the summary cards is too big, it will create an empty space like in the screenshot below:

![screen shot 2560-02-03 at 12 43 15 pm](https://cloud.githubusercontent.com/assets/2647689/22580846/63c53462-ea0e-11e6-9728-eb2b49ed0714.png)

We can fix it by adding a `.row` class every 2 records. That also means we cannot display more cards per row in the future (but one card per row for the mobile version is fine).

Let me know if you want me to proceed with this.

**Comment by ptrikutam** [comment]
This should be fine, please proceed
