### ISSUE TITLE
Common Date Field for Groups/Resources/Lists/Users

### ISSUE THREAD

**Issue by T-Dnzt** [greencommons/commons#123]
As mentioned in PR #117, we need to have a unique column containing the date that will be used to sort the records when different models are returned.

For all of them, we can use the date present in the metadata if there's one, or fall back to the `created_at` date. I guess we could call the field `date` or `published_at` maybe?

Let me know if you want me to proceed with this.

**Comment by ptrikutam** [comment]
Let's go with `published_at`. Please proceed!

**Comment by T-Dnzt** [comment]
I guess we can close this issue :)
