### ISSUE TITLE
(M) Homepage: last button under carousel in Connect in Networks doesn’t do anything.

### ISSUE THREAD

**Issue by ptrikutam** [greencommons/commons#189]
Demonstration of issue: https://cl.ly/2P2f002y3h0p

**Comment by nsanta** [comment]
Also the last button is displayed below the other buttons in the carousel
<img width="973" alt="last_dot_connect" src="https://user-images.githubusercontent.com/15721/30177868-77849f82-93dd-11e7-8eae-4c12287a9e01.png">

**Comment by ptrikutam** [comment]
@nsanta good call. This seems to be a screen size issue, as when I have my window maximized it doesn't happen, but happens as I resize the window: https://cl.ly/12202s320a2a

Can you see if you're able to find a fix for both (so that the dots always are on one row?
