### ISSUE TITLE
Error message when clicking "Create a List"

### ISSUE THREAD

**Issue by ptrikutam** [greencommons/commons#204]
Clicking on Create a List box, logged In, gave a “you are already logged in” bar across page. Didn’t repeat after returning to Home and clicking again.

This will be fixed with https://github.com/greencommons/commons/issues/262

**Comment by ptrikutam** [comment]
@nsanta please see if you can reproduce once you've fixed #262. If not, feel free to move to "Done" and close.

**Comment by nsanta** [comment]
Seems to be fixed.
