### ISSUE TITLE
Add steps to the bin/setup script to handle ElasticSearch setup

### ISSUE THREAD

**Issue by ptrikutam** [greencommons/commons#23]

**Comment by adarsh** [comment]
Handled by https://github.com/greencommons/commons/pull/31, although this does not include the Java requirement, which seems intense to do automatically for a user.

Thoughts?

**Comment by ptrikutam** [comment]
Isn't that automatically handled by homebrew? Regardless, I feel like it's fine to leave that out.

**Comment by adarsh** [comment]
Agreed. Closing.
