### ISSUE TITLE
Decouple RSpec from needing ElasticSearch to have a green test suite

### ISSUE THREAD

**Issue by ptrikutam** [greencommons/commons#25]
Currently, the front-runner for how to do this is to use Webmock to mock any request to `http://localhost:9200`

**Comment by adarsh** [comment]
One idea I had:

If we set these callbacks to run asynchronously (e.g. spin up a Sidekiq job to change the search index), we can have a bit more control over when we actually update the index.

For example, we could handle errors more gracefully. Or just not execute the job in `development` or `test` environments unless some `ENV` is set. 

https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-model#asynchronous-callbacks

**Comment by ptrikutam** [comment]
I really like this idea. Want to make a separate issue for it?

You can edit this issue to indicate it's dependent on that one. Furthermore, we should probably set up an issue to set up Sidekiq as well.

**Comment by adarsh** [comment]
Done! It's here: https://github.com/greencommons/commons/issues/33

**Comment by adarsh** [comment]
This is handled by making everything asychronous anyhow in https://github.com/greencommons/commons/pull/36. Closing!
