### ISSUE TITLE
JSON results do not include basic bibliographic metadata. (Consider using Dublin Core for the schema.)

### ISSUE THREAD

**Issue by gtourtellot** [greencommons/commons#252]
Request from @dweinberger.  Priority should be fairly high (i.e., in "Up Next") since this is blocking his app development.

**Comment by ptrikutam** [comment]
@dweinberger / @gtourtellot -- we've updated the API to return all metadata with each request in https://github.com/greencommons/commons/pull/251.

Are you still having issues?

**Comment by ptrikutam** [comment]
Closing this until there is confirmation that it's still happening. If it is still occurring, feel free to reopen!
