### ISSUE TITLE
Deleting Resources has a race condition

### ISSUE THREAD

**Issue by adarsh** [greencommons/commons#43]
> I ran into this issue (after previously manually deleting record 100): https://cl.ly/2x2c1r1I0W26

So that pic is showing errors where the job is failing because it's trying to find record 100 but it doesn't exist. That's a bug - we are asking ES to remove a record from the index which does not exist in the database anymore :(

I'm opening an issue for this. Solution is probably a separate delete job, something like "don't try to rehydrate the AR record when you are deleting it - just use what the job was sent."

**Comment by T-Dnzt** [comment]
@ptrikutam I think we can close this issue.
