### ISSUE TITLE
Rake task to clear the ElasticSearch index

### ISSUE THREAD

**Issue by ptrikutam** [greencommons/commons#45]
Sometimes when running `rake db:reset` the index doesn't get reset. Would be good to have a rake task to handle this. All it needs to do is:

```
client = Elasticsearch::Client.new log:true
client.indices.delete index: 'resources'
```

**Comment by adarsh** [comment]
This looks to be covered by https://github.com/greencommons/commons/pull/51.

Closing unless I got something wrong.
