### ISSUE TITLE
Add group view page

### ISSUE THREAD

**Issue by ptrikutam** [greencommons/commons#61]
Based on [the wireframes for the Group View page](https://invis.io/BH8GKH38D#/185307852_GROUP_-_View), please start coding up a skeleton for the Group view.

Some points about functionality:

- A `Group` can have many `List`s. Each of these `List`s will have many resources -- anyone in a group can modify a `List` that belongs to the `Group`.
- In the "What's New" section, we want to display recent items that have been added to any `List` owned by the `Group`. This might require creating some kind of helper method / scope on `Group` to access all of its `Resource`s through its various `List`s. Open to discussion on the best way to approach this.
- Clicking the "See More" link should display the rest of the Group's metadata, such as the description, website, created date, etc.
- Anyone can view a group, even if they're not a member
- Anyone can view a group's member list, even if they're not a member
- The ["Leave Group" button](https://cl.ly/403W1A0V3M41) should only appear if you're a member of the group
- Please leave out the "Add to List" button for now.

**Comment by T-Dnzt** [comment]
This is the summary card for a group:

![screen shot 2559-12-14 at 8 18 18 pm](https://cloud.githubusercontent.com/assets/2647689/21183444/849beaa6-c23a-11e6-82a2-d27dbb65c366.png)

And this for a resource:

![screen shot 2559-12-14 at 8 18 21 pm](https://cloud.githubusercontent.com/assets/2647689/21183446/8ad1f2c6-c23a-11e6-88fe-521f675dc5f1.png)

As you can see the tags/metadata are not presented in the same order on both. Do we want to unify this or should I implement the two different styles?

**Comment by T-Dnzt** [comment]
I have a skeleton on the view and I'm wondering about the button colors. Either I can have them all blue, or use different colors depending on the action type as shown in the screenshot below. Blue for GET, green for POST and red for DELETE:

![screen shot 2559-12-14 at 9 08 54 pm](https://cloud.githubusercontent.com/assets/2647689/21185011/8ac9264e-c241-11e6-94ae-0cdd4955e588.png)

**Comment by T-Dnzt** [comment]
A basic version of the group view page is available in this [PR](https://github.com/greencommons/commons/pull/83). There's nothing dynamic yet and a lot of fake data.

**Comment by ptrikutam** [comment]
> As you can see the tags/metadata are not presented in the same order on both. Do we want to unify this or should I implement the two different styles?

Good catch. Feel free to use your best judgement and unify the styles as you see fit.

> I have a skeleton on the view and I'm wondering about the button colors. Either I can have them all blue, or use different colors depending on the action type as shown in the screenshot below. 

Hmm... Let's avoid using the red or green color for now. Let's keep all the buttons blue for now, except for the leave group button -- let's make that one white (`.btn-default`). 

>Also, what do you think of having the Back button like this instead of just the << Back blue link?


The back button looks good, I like it.
