### ISSUE TITLE
Add Capybara tests for the Group Functionality

### ISSUE THREAD

**Issue by T-Dnzt** [greencommons/commons#74]
There are currently no complete feature tests to ensure that the various parts of the Group Functionality work as expected. 

Here are the happy path scenarios that have to be implemented as acceptance tests:

- [x] `scenario 'users can create a group'`
- [x] `scenario 'users can update a group'`
- [x] `scenario 'users can add members'`
- [x] `scenario 'users can remove members'`
- [x] `scenario 'users can make other members admins'`
- [x] `scenario 'users can remove admin from other members'`

Some of these scenarios might get merge together to have faster tests.

**Comment by ptrikutam** [comment]
Great idea. Please do flesh this issue out once you're done w/ the Group PR.
