### ISSUE TITLE
Add Group Summary card to /style

### ISSUE THREAD

**Issue by ptrikutam** [greencommons/commons#79]
Can you add an example of the group summary card (and a code snippet of its usage in Rails) on the `/style` page? I'd like to keep an up-to-date list of all the reusable components we create.

**Comment by T-Dnzt** [comment]
Would you like to have syntax coloration for the code examples?

**Comment by T-Dnzt** [comment]
Is [this](https://github.com/greencommons/commons/pull/82) what you had in mind?

**Comment by ptrikutam** [comment]
Going to respond to your Qs on the PR itself.
