### ISSUE TITLE
Load books from Amazon S3 into index on production

### ISSUE THREAD

**Issue by ptrikutam** [greencommons/commons#87]
Please run the rake task `rake etl:import_s3_epub` on production (https://greencommons.herokuapp.com).

To do it, I imagine we need to do the following steps:

- [x] Add @T-Dnzt to Heroku
- [x] Provide @T-Dnzt with S3 access
- [x] Update the [environment variables for S3](https://github.com/greencommons/commons/blob/master/.env.sample#L4-L6) on Heroku
- [x] Clear the database of any existing `List` and `Resource` objects
- [x] Run the rake task to import the actual books
- [x] Do a quick check in Sidekiq to make sure things are being indexed properly
- [x] Do a quick check on the site by searching for one of the books and ensuring it comes up in the search results.
- [x] Create some dummy lists in the back end for the Groups in the database with some of these Resources

**Comment by T-Dnzt** [comment]
I created some dummy lists and groups in the database. If you're happy with it, I will close this issue :)

**Comment by ptrikutam** [comment]
Awesome, thanks @T-Dnzt. Do you think it makes sense to update the `seeds.rb` file to include the newly updated Resources?

**Comment by T-Dnzt** [comment]
Hmm, not sure I follow. What do you mean by including them in the `seeds.rb` file?

**Comment by ptrikutam** [comment]
Basically, as opposed to creating new Resources in seeds.rb, using the ones in the index.

That said, on second thought, i think that's probably a bad idea -- we probably shouldn't be using real data in the Seeds file. Unless you disagree, I'm going to close this. Thanks!
