### ISSUE TITLE
ElasticSearch indexing fails in production

### ISSUE THREAD

**Issue by T-Dnzt** [greencommons/commons#96]
Currently, Sidekiq fails to add new resources to the ElasticSearch index in production with the following error:

```
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] 
{"error":
  {
    "root_cause":
      [{"type":"mapper_parsing_exception","reason":"object mapping for [content] tried to parse field [content] as object, but found a concrete value"}],
    "type":"mapper_parsing_exception","reason":"object mapping for [content] tried to parse field [content] as object, but found a concrete value"
  },
 "status":400
}
``` 

This might be related to [issue 97](https://github.com/greencommons/commons/issues/97) (or maybe not).

**Comment by ptrikutam** [comment]
A few searches led me to:

https://stackoverflow.com/questions/30454108/how-to-solve-mapperparsingexception-object-mapping-for-test-tried-to-parse-as

https://github.com/elastic/elasticsearch/issues/2354

It seems like we may be having different values for the "Content" field in what we're putting into the database.

Perhaps it's worth doing a full reset of the DB (deleting all users, resources, etc) and then loading in only the resources before anything else. What do you think @T-Dnzt?

**Comment by T-Dnzt** [comment]
I think I will try a full reset once the PR fixing the index name is live. From there, we can see which issues are left and fix them.

**Comment by T-Dnzt** [comment]
I cleared the index and I'm currently re-running the import task without any issues. Closing this issue as it seems to be resolved.
