### ISSUE TITLE
Search Results Page

### ISSUE THREAD

**Issue by ptrikutam** [greencommons/commons#98]
We want to build out the Search results page: https://invis.io/BH8GKH38D#/185307864_SEARCH

This will involve a few different things:

- [x] Taking the search term entered and searching across `Group`, `Resource`, and `List` to begin with. The search page should return a list of all items combined together.
- [x] If they don't already exist, we need to create summary cards for different search result items.
- [x] Building out the left-hand filter list. We should discuss what types of filters actually belong in this section. At the minimum, we should be able to filter by Group, Resource, and List.
- [x] Allow sorting by Date or "Relevance" (see "Stackscore / Relevancy" below)
- [x] Ensure we can paginate search results

## Stackscore / Relevancy

@dweinberger wants to assign a "Stackscore" or "Relevancy" number to every search result we get. This can be a number between 0 and 100 or something similar, but ultimately is a "smart" determination of what an item's relevancy is to what you've searched for. Initially, we can make this very simple, but we should build a stub or foundation to expand and make this more sophisticated as we go along. I'm happy to walk through this via a audio / video chat.

## "You may also like"

Not pictured in the wireframes, we want to include a small section below the search results that provides suggestions on other things a user may be interested in. Initially, we can keep it simple, and the recommendations can be rather uninteresting, but it'd be good to set up a way to see "related items" based on a search term or an actual object in the database. This is somewhat similar in idea to "Stackscore / Relevancy," so it's worth discussing what makes sense here.

**NOTE**: This is a rather large task, so if it makes sense, feel free to break this up into smaller issues and re-order as you see fit.

**Comment by T-Dnzt** [comment]
I guess we can close this issue :) If I forgot anything, let me know!
