### ISSUE TITLE
Resource View Page

### ISSUE THREAD

**Issue by ptrikutam** [greencommons/commons#99]
Wireframes: https://invis.io/BH8GKH38D#/185307862_RESOURCE_-_View

We'd like to build out the base UI for the Resource page.

Most of it should be straightforward, but for sake of specificity I'd like to clarify a few things:

- For the time being, please ignore (don't display) the "Discuss" section
- Please skip the "Content" section for now.
- Try to extract the actual metadata for the Resource in the "About" section -- currently we're pulling Title, Creators, Date (publish date), Publisher, and a "Metadata" field. Can you investigate what type of data is included in the "Metadata" field and see if we can extract that to be displayed in the Resource view?
- For the "Explore" section, let's go for things that share the same tags to start. Ideally, this should use a similar mechanism as the one described in https://github.com/greencommons/commons/issues/98 in the "You May Also Like" section. Basically, we want a centralized place to recommend similar / related (directly or tangentially) items for a given resource, list, group, etc. Happy to talk through this part.

**Comment by T-Dnzt** [comment]
Maybe we can close this? :)
